// Static country data to be used when external API is not available
export const countryData = [
  {
    name: "United States",
    alpha2Code: "US",
    alpha3Code: "USA",
    capital: "Washington, D.C.",
    region: "Americas",
    subregion: "North America",
    population: 331002651,
    area: 9372610,
    flagUrl: "https://flagcdn.com/us.svg",
    coatOfArmsUrl: "https://mainfacts.com/media/images/coats_of_arms/us.png",
    mapUrl: "https://goo.gl/maps/e8M246zY4BSjkjAv6",
    independent: true,
    unMember: true,
    currencies: { USD: { name: "United States dollar", symbol: "$" } },
    languages: { eng: "English" },
    borders: ["CAN", "MEX"],
    timezones: ["UTC-12:00", "UTC-11:00", "UTC-10:00", "UTC-09:00", "UTC-08:00", "UTC-07:00", "UTC-06:00", "UTC-05:00", "UTC-04:00", "UTC+10:00", "UTC+12:00"],
    startOfWeek: "sunday",
    capitalInfo: { latlng: [38.89, -77.05] },
    postalCode: { format: "#####-####", regex: "^\\d{5}(-\\d{4})?$" },
    flag: "🇺🇸",
    countryInfo: {
      capital: "Washington, D.C.",
      region: "Americas",
      subregion: "North America",
      population: 331002651,
      governmentForm: "Federal presidential constitutional republic",
    }
  },
  {
    name: "United Kingdom",
    alpha2Code: "GB",
    alpha3Code: "GBR",
    capital: "London",
    region: "Europe",
    subregion: "Northern Europe",
    population: 67886011,
    area: 242900,
    flagUrl: "https://flagcdn.com/gb.svg",
    coatOfArmsUrl: "https://mainfacts.com/media/images/coats_of_arms/gb.png",
    mapUrl: "https://goo.gl/maps/FoDtc3UKMkFsXAjHA",
    independent: true,
    unMember: true,
    currencies: { GBP: { name: "British pound", symbol: "£" } },
    languages: { eng: "English" },
    borders: ["IRL"],
    timezones: ["UTC-08:00", "UTC-05:00", "UTC-04:00", "UTC-03:00", "UTC-02:00", "UTC", "UTC+01:00", "UTC+02:00", "UTC+06:00"],
    startOfWeek: "monday",
    capitalInfo: { latlng: [51.5, -0.08] },
    postalCode: { format: "@# #@@|@## #@@|@@# #@@|@@## #@@|@#@ #@@|@@#@ #@@|GIR0AA", regex: "^(([A-Z]\\d{2}[A-Z]{2})|([A-Z]\\d{3}[A-Z]{2})|([A-Z]{2}\\d{2}[A-Z]{2})|([A-Z]{2}\\d{3}[A-Z]{2})|([A-Z]\\d[A-Z]\\d[A-Z]{2})|([A-Z]{2}\\d[A-Z]\\d[A-Z]{2})|(GIR0AA))$" },
    flag: "🇬🇧",
    countryInfo: {
      capital: "London",
      region: "Europe",
      subregion: "Northern Europe",
      population: 67886011,
      governmentForm: "Unitary parliamentary constitutional monarchy",
    }
  },
  {
    name: "France",
    alpha2Code: "FR",
    alpha3Code: "FRA",
    capital: "Paris",
    region: "Europe",
    subregion: "Western Europe",
    population: 67391582,
    area: 551695,
    flagUrl: "https://flagcdn.com/fr.svg",
    coatOfArmsUrl: "https://mainfacts.com/media/images/coats_of_arms/fr.png",
    mapUrl: "https://goo.gl/maps/g7QxxSFsWyTPKuzd7",
    independent: true,
    unMember: true,
    currencies: { EUR: { name: "Euro", symbol: "€" } },
    languages: { fra: "French" },
    borders: ["AND", "BEL", "DEU", "ITA", "LUX", "MCO", "ESP", "CHE"],
    timezones: ["UTC-10:00", "UTC-09:30", "UTC-09:00", "UTC-08:00", "UTC-04:00", "UTC-03:00", "UTC+01:00", "UTC+02:00", "UTC+03:00", "UTC+04:00", "UTC+05:00", "UTC+10:00", "UTC+11:00", "UTC+12:00"],
    startOfWeek: "monday",
    capitalInfo: { latlng: [48.87, 2.33] },
    postalCode: { format: "#####", regex: "^(\\d{5})$" },
    flag: "🇫🇷",
    countryInfo: {
      capital: "Paris",
      region: "Europe",
      subregion: "Western Europe",
      population: 67391582,
      governmentForm: "Unitary semi-presidential republic",
    }
  },
  {
    name: "Germany",
    alpha2Code: "DE",
    alpha3Code: "DEU",
    capital: "Berlin",
    region: "Europe",
    subregion: "Western Europe",
    population: 83240525,
    area: 357114,
    flagUrl: "https://flagcdn.com/de.svg",
    coatOfArmsUrl: "https://mainfacts.com/media/images/coats_of_arms/de.png",
    mapUrl: "https://goo.gl/maps/mD9FBMq1nvXUBrkv6",
    independent: true,
    unMember: true,
    currencies: { EUR: { name: "Euro", symbol: "€" } },
    languages: { deu: "German" },
    borders: ["AUT", "BEL", "CZE", "DNK", "FRA", "LUX", "NLD", "POL", "CHE"],
    timezones: ["UTC+01:00"],
    startOfWeek: "monday",
    capitalInfo: { latlng: [52.52, 13.4] },
    postalCode: { format: "#####", regex: "^(\\d{5})$" },
    flag: "🇩🇪",
    countryInfo: {
      capital: "Berlin",
      region: "Europe",
      subregion: "Western Europe",
      population: 83240525,
      governmentForm: "Federal parliamentary republic",
    }
  },
  {
    name: "Japan",
    alpha2Code: "JP",
    alpha3Code: "JPN",
    capital: "Tokyo",
    region: "Asia",
    subregion: "Eastern Asia",
    population: 125836021,
    area: 377930,
    flagUrl: "https://flagcdn.com/jp.svg",
    coatOfArmsUrl: "https://mainfacts.com/media/images/coats_of_arms/jp.png",
    mapUrl: "https://goo.gl/maps/NGTLSCSrA8bMrvnX9",
    independent: true,
    unMember: true,
    currencies: { JPY: { name: "Japanese yen", symbol: "¥" } },
    languages: { jpn: "Japanese" },
    borders: [],
    timezones: ["UTC+09:00"],
    startOfWeek: "monday",
    capitalInfo: { latlng: [35.68, 139.75] },
    postalCode: { format: "###-####", regex: "^(\\d{7})$" },
    flag: "🇯🇵",
    countryInfo: {
      capital: "Tokyo",
      region: "Asia",
      subregion: "Eastern Asia",
      population: 125836021,
      governmentForm: "Unitary parliamentary constitutional monarchy",
    }
  },
  {
    name: "China",
    alpha2Code: "CN",
    alpha3Code: "CHN",
    capital: "Beijing",
    region: "Asia",
    subregion: "Eastern Asia",
    population: 1402112000,
    area: 9640011,
    flagUrl: "https://flagcdn.com/cn.svg",
    coatOfArmsUrl: "https://mainfacts.com/media/images/coats_of_arms/cn.png",
    mapUrl: "https://goo.gl/maps/p9qC6vgiFRRXtasE8",
    independent: true,
    unMember: true,
    currencies: { CNY: { name: "Chinese yuan", symbol: "¥" } },
    languages: { zho: "Chinese" },
    borders: ["AFG", "BTN", "MMR", "HKG", "IND", "KAZ", "PRK", "KGZ", "LAO", "MAC", "MNG", "PAK", "RUS", "TJK", "VNM", "NPL"],
    timezones: ["UTC+08:00"],
    startOfWeek: "monday",
    capitalInfo: { latlng: [39.92, 116.38] },
    postalCode: { format: "######", regex: "^(\\d{6})$" },
    flag: "🇨🇳",
    countryInfo: {
      capital: "Beijing",
      region: "Asia",
      subregion: "Eastern Asia",
      population: 1402112000,
      governmentForm: "Unitary Marxist–Leninist one-party socialist republic",
    }
  },
  {
    name: "Russia",
    alpha2Code: "RU",
    alpha3Code: "RUS",
    capital: "Moscow",
    region: "Europe",
    subregion: "Eastern Europe",
    population: 144104080,
    area: 17098242,
    flagUrl: "https://flagcdn.com/ru.svg",
    coatOfArmsUrl: "https://mainfacts.com/media/images/coats_of_arms/ru.png",
    mapUrl: "https://goo.gl/maps/4F4PpDhGJgVvLby57",
    independent: true,
    unMember: true,
    currencies: { RUB: { name: "Russian ruble", symbol: "₽" } },
    languages: { rus: "Russian" },
    borders: ["AZE", "BLR", "CHN", "EST", "FIN", "GEO", "KAZ", "PRK", "LVA", "LTU", "MNG", "NOR", "POL", "UKR"],
    timezones: ["UTC+03:00", "UTC+04:00", "UTC+06:00", "UTC+07:00", "UTC+08:00", "UTC+09:00", "UTC+10:00", "UTC+11:00", "UTC+12:00"],
    startOfWeek: "monday",
    capitalInfo: { latlng: [55.75, 37.6] },
    postalCode: { format: "######", regex: "^(\\d{6})$" },
    flag: "🇷🇺",
    countryInfo: {
      capital: "Moscow",
      region: "Europe",
      subregion: "Eastern Europe",
      population: 144104080,
      governmentForm: "Federal semi-presidential republic",
    }
  },
  {
    name: "Brazil",
    alpha2Code: "BR",
    alpha3Code: "BRA",
    capital: "Brasília",
    region: "Americas",
    subregion: "South America",
    population: 212559417,
    area: 8515767,
    flagUrl: "https://flagcdn.com/br.svg",
    coatOfArmsUrl: "https://mainfacts.com/media/images/coats_of_arms/br.png",
    mapUrl: "https://goo.gl/maps/waCKk21HeeqFzkNC9",
    independent: true,
    unMember: true,
    currencies: { BRL: { name: "Brazilian real", symbol: "R$" } },
    languages: { por: "Portuguese" },
    borders: ["ARG", "BOL", "COL", "GUF", "GUY", "PRY", "PER", "SUR", "URY", "VEN"],
    timezones: ["UTC-05:00", "UTC-04:00", "UTC-03:00", "UTC-02:00"],
    startOfWeek: "monday",
    capitalInfo: { latlng: [-15.79, -47.88] },
    postalCode: { format: "#####-###", regex: "^(\\d{8})$" },
    flag: "🇧🇷",
    countryInfo: {
      capital: "Brasília",
      region: "Americas",
      subregion: "South America",
      population: 212559417,
      governmentForm: "Federal presidential constitutional republic",
    }
  },
  {
    name: "Australia",
    alpha2Code: "AU",
    alpha3Code: "AUS",
    capital: "Canberra",
    region: "Oceania",
    subregion: "Australia and New Zealand",
    population: 25499884,
    area: 7692024,
    flagUrl: "https://flagcdn.com/au.svg",
    coatOfArmsUrl: "https://mainfacts.com/media/images/coats_of_arms/au.png",
    mapUrl: "https://goo.gl/maps/DcjaDa7UbhnZTndH6",
    independent: true,
    unMember: true,
    currencies: { AUD: { name: "Australian dollar", symbol: "$" } },
    languages: { eng: "English" },
    borders: [],
    timezones: ["UTC+05:00", "UTC+06:30", "UTC+07:00", "UTC+08:00", "UTC+09:30", "UTC+10:00", "UTC+10:30", "UTC+11:30"],
    startOfWeek: "monday",
    capitalInfo: { latlng: [-35.27, 149.13] },
    postalCode: { format: "####", regex: "^(\\d{4})$" },
    flag: "🇦🇺",
    countryInfo: {
      capital: "Canberra",
      region: "Oceania",
      subregion: "Australia and New Zealand",
      population: 25499884,
      governmentForm: "Federal parliamentary constitutional monarchy",
    }
  },
  {
    name: "Switzerland",
    alpha2Code: "CH",
    alpha3Code: "CHE",
    capital: "Bern",
    region: "Europe",
    subregion: "Western Europe",
    population: 8654622,
    area: 41284,
    flagUrl: "https://flagcdn.com/ch.svg",
    coatOfArmsUrl: "https://mainfacts.com/media/images/coats_of_arms/ch.png",
    mapUrl: "https://goo.gl/maps/uVuZcXaxSx5jLyEC9",
    independent: true,
    unMember: true,
    currencies: { CHF: { name: "Swiss franc", symbol: "Fr." } },
    languages: { fra: "French", gsw: "Swiss German", ita: "Italian", roh: "Romansh" },
    borders: ["AUT", "FRA", "ITA", "LIE", "DEU"],
    timezones: ["UTC+01:00"],
    startOfWeek: "monday",
    capitalInfo: { latlng: [46.92, 7.47] },
    postalCode: { format: "####", regex: "^(\\d{4})$" },
    flag: "🇨🇭",
    countryInfo: {
      capital: "Bern",
      region: "Europe",
      subregion: "Western Europe",
      population: 8654622,
      governmentForm: "Federal semi-direct democracy under a multi-party parliamentary directorial republic",
    }
  },
  {
    name: "South Africa",
    alpha2Code: "ZA",
    alpha3Code: "ZAF",
    capital: "Pretoria",
    region: "Africa",
    subregion: "Southern Africa",
    population: 59308690,
    area: 1221037,
    flagUrl: "https://flagcdn.com/za.svg",
    coatOfArmsUrl: "https://mainfacts.com/media/images/coats_of_arms/za.png",
    mapUrl: "https://goo.gl/maps/CLCZ1R8Uz1KpZhng6",
    independent: true,
    unMember: true,
    currencies: { ZAR: { name: "South African rand", symbol: "R" } },
    languages: { afr: "Afrikaans", eng: "English", nbl: "Southern Ndebele", nso: "Northern Sotho", sot: "Southern Sotho", ssw: "Swazi", tsn: "Tswana", tso: "Tsonga", ven: "Venda", xho: "Xhosa", zul: "Zulu" },
    borders: ["BWA", "LSO", "MOZ", "NAM", "SWZ", "ZWE"],
    timezones: ["UTC+02:00"],
    startOfWeek: "monday",
    capitalInfo: { latlng: [-25.7, 28.22] },
    postalCode: { format: "####", regex: "^(\\d{4})$" },
    flag: "🇿🇦",
    countryInfo: {
      capital: "Pretoria",
      region: "Africa",
      subregion: "Southern Africa",
      population: 59308690,
      governmentForm: "Unitary parliamentary constitutional republic",
    }
  },
  {
    name: "Egypt",
    alpha2Code: "EG",
    alpha3Code: "EGY",
    capital: "Cairo",
    region: "Africa",
    subregion: "Northern Africa",
    population: 102334404,
    area: 1002450,
    flagUrl: "https://flagcdn.com/eg.svg",
    coatOfArmsUrl: "https://mainfacts.com/media/images/coats_of_arms/eg.png",
    mapUrl: "https://goo.gl/maps/uVuZcXaxSx5jLyEC9",
    independent: true,
    unMember: true,
    currencies: { EGP: { name: "Egyptian pound", symbol: "£" } },
    languages: { ara: "Arabic" },
    borders: ["ISR", "LBY", "SDN"],
    timezones: ["UTC+02:00"],
    startOfWeek: "saturday",
    capitalInfo: { latlng: [30.05, 31.25] },
    postalCode: { format: "#####", regex: "^(\\d{5})$" },
    flag: "🇪🇬",
    countryInfo: {
      capital: "Cairo",
      region: "Africa",
      subregion: "Northern Africa",
      population: 102334404,
      governmentForm: "Unitary semi-presidential republic",
    }
  },
  {
    name: "India",
    alpha2Code: "IN",
    alpha3Code: "IND",
    capital: "New Delhi",
    region: "Asia",
    subregion: "Southern Asia",
    population: 1380004385,
    area: 3287590,
    flagUrl: "https://flagcdn.com/in.svg",
    coatOfArmsUrl: "https://mainfacts.com/media/images/coats_of_arms/in.png",
    mapUrl: "https://goo.gl/maps/WSk3fLwG4vtPQetp7",
    independent: true,
    unMember: true,
    currencies: { INR: { name: "Indian rupee", symbol: "₹" } },
    languages: { eng: "English", hin: "Hindi", tam: "Tamil" },
    borders: ["AFG", "BGD", "BTN", "MMR", "CHN", "NPL", "PAK", "LKA"],
    timezones: ["UTC+05:30"],
    startOfWeek: "monday",
    capitalInfo: { latlng: [28.6, 77.2] },
    postalCode: { format: "######", regex: "^(\\d{6})$" },
    flag: "🇮🇳",
    countryInfo: {
      capital: "New Delhi",
      region: "Asia",
      subregion: "Southern Asia",
      population: 1380004385,
      governmentForm: "Federal parliamentary constitutional republic",
    }
  },
  {
    name: "Canada",
    alpha2Code: "CA",
    alpha3Code: "CAN",
    capital: "Ottawa",
    region: "Americas",
    subregion: "North America",
    population: 38005238,
    area: 9984670,
    flagUrl: "https://flagcdn.com/ca.svg",
    coatOfArmsUrl: "https://mainfacts.com/media/images/coats_of_arms/ca.png",
    mapUrl: "https://goo.gl/maps/jmEVLugreeqiZXxbA",
    independent: true,
    unMember: true,
    currencies: { CAD: { name: "Canadian dollar", symbol: "$" } },
    languages: { eng: "English", fra: "French" },
    borders: ["USA"],
    timezones: ["UTC-08:00", "UTC-07:00", "UTC-06:00", "UTC-05:00", "UTC-04:00", "UTC-03:30"],
    startOfWeek: "sunday",
    capitalInfo: { latlng: [45.42, -75.7] },
    postalCode: { format: "@#@ #@#", regex: "^([ABCEGHJKLMNPRSTVXY]\\d[ABCEGHJKLMNPRSTVWXYZ]) ?(\\d[ABCEGHJKLMNPRSTVWXYZ]\\d)$" },
    flag: "🇨🇦",
    countryInfo: {
      capital: "Ottawa",
      region: "Americas",
      subregion: "North America",
      population: 38005238,
      governmentForm: "Federal parliamentary constitutional monarchy",
    }
  },
  {
    name: "South Korea",
    alpha2Code: "KR",
    alpha3Code: "KOR",
    capital: "Seoul",
    region: "Asia",
    subregion: "Eastern Asia",
    population: 51780579,
    area: 100210,
    flagUrl: "https://flagcdn.com/kr.svg",
    coatOfArmsUrl: "https://mainfacts.com/media/images/coats_of_arms/kr.png",
    mapUrl: "https://goo.gl/maps/7ecjaJXefjAQhxjGA",
    independent: true,
    unMember: true,
    currencies: { KRW: { name: "South Korean won", symbol: "₩" } },
    languages: { kor: "Korean" },
    borders: ["PRK"],
    timezones: ["UTC+09:00"],
    startOfWeek: "monday",
    capitalInfo: { latlng: [37.55, 126.98] },
    postalCode: { format: "SEOUL #####", regex: "^(?:SEOUL)*(\\d{5})$" },
    flag: "🇰🇷",
    countryInfo: {
      capital: "Seoul",
      region: "Asia",
      subregion: "Eastern Asia",
      population: 51780579,
      governmentForm: "Unitary presidential constitutional republic",
    }
  },
  {
    name: "South Georgia",
    alpha2Code: "GS",
    alpha3Code: "SGS",
    capital: "King Edward Point",
    region: "Antarctic",
    subregion: "South Atlantic Ocean",
    population: 30,
    area: 3903,
    flagUrl: "https://flagcdn.com/gs.svg",
    coatOfArmsUrl: null,
    mapUrl: "https://goo.gl/maps/mJzdaBwKBbm2B81q9",
    independent: false,
    unMember: false,
    currencies: { GBP: { name: "Pound sterling", symbol: "£" } },
    languages: { eng: "English" },
    borders: [],
    timezones: ["UTC-02:00"],
    startOfWeek: "monday",
    capitalInfo: { latlng: [-54.28, -36.5] },
    postalCode: null,
    flag: "🇬🇸",
    countryInfo: {
      capital: "King Edward Point",
      region: "Antarctic",
      subregion: "South Atlantic Ocean",
      population: 30,
      governmentForm: "British Overseas Territory",
    }
  }
];